const metroData = [
{
    "route": "Red Line",
    "line": "Red",
    "parentStopIds":["MYP","JNT","KPH","KUK","BLR","MSP","BTN","ERA","ESI","SRN","AME","PUN","IRM","KHA","LKP","ASM","NAM","GAB","OMC","MGB","MKL","NEM","MSB","DSN","CHP","VOM","LBN"],
    "stops-1-way-stopIds": ["MYP1","JNT1","KPH1","KUK1","BLR1","MSP1","BTN1","ERA1","ESI1","SRN1","AME3","PUN1","IRM1","KHA1","LKP1","ASM1","NAM1","GAB1","OMC1","MGB3","MKL1","NEM1","MSB1","DSN1","CHP1","VOM1","LBN1"],
    "stops-2-way-stopIds": ["LBN2","VOM2","CHP2","DSN2","MSB2","NEM2","MKL2","MGB4","OMC2","GAB2","NAM2","ASM2","LKP2","KHA2","IRM2","PUN2","AME4","SRN2","ESI2","ERA2","BTN2","MSP2","BLR2","KUK2","KPH2","JNT2","MYP2"],
    "stops-1-way":[  
        {
            "stopId": "MYP1",
            "stopName":"Miyapur",
            "lat": 17.4965452,
            "long": 78.3730262,
            "zone": "MYP",
            "locationType": 0,
            "parentStation": "MYP",
            "platformCode": 1,
            "nextStop": "JNT1"
        },
        {
            "stopId":"JNT1",
            "stopName":"JNTU College",
            "lat": 17.4987037,
            "long": 78.3888668,
            "zone": "JNT",
            "locationType": 0,
            "parentStation": "JNT",
            "platformCode": 1,
            "nextStop": "KPH1"
        },
        {
            "stopId":"KPH1",
            "stopName":"KPHB",
            "lat": 17.4937602,
            "long": 78.4018258,
            "zone": "KPH",
            "locationType": 0,
            "parentStation": "KPH",
            "platformCode": 1,
            "nextStop": "KUK1"
        },
        {
            "stopId":"KUK1",
            "stopName":"Kukatpally",
            "lat": 17.4849033,
            "long": 78.4117896,
            "zone": "KUK",
            "locationType": 0,
            "parentStation": "KUK",
            "platformCode": 1,
            "nextStop": "BLR1"
        },
        {
            "stopId":"BLR1",
            "stopName":"Balanagar",
            "lat": 17.4767464,
            "long": 78.4221082,
            "zone": "BLR",
            "locationType": 0,
            "parentStation": "BLR",
            "platformCode": 1,
            "nextStop": "MSP1"
        },
        {
            "stopId":"MSP1",
            "stopName":"Moosapet",
            "lat": 17.4718855,
            "long": 78.4261182,
            "zone": "MSP",
            "locationType": 0,
            "parentStation": "MSP",
            "platformCode": 1,
            "nextStop": "BTN1"
        },
        {
            "stopId":"BTN1",
            "stopName":"Bharat Nagar",
            "lat": 17.4629092,
            "long": 78.4305364,
            "zone": "BTN",
            "locationType": 0,
            "parentStation": "BTN",
            "platformCode": 1,
            "nextStop": "ERA1"
        },
        {
            "stopId":"ERA1",
            "stopName":"Erragadda",
            "lat": 17.4570487,
            "long": 78.4335811,
            "zone": "ERA",
            "locationType": 0,
            "parentStation": "ERA",
            "platformCode": 1,
            "nextStop": "ESI1"
        },
        {
            "stopId":"ESI1",
            "stopName":"ESI Hospital",
            "lat": 17.4486969,
            "long": 78.4376283,
            "zone": "ESI",
            "locationType": 0,
            "parentStation": "ESI",
            "platformCode": 1,
            "nextStop": "SRN1"
        },
        {
            "stopId":"SRN1",
            "stopName":"S. R. Nagar",
            "lat": 17.4431205,
            "long": 78.4407241,
            "zone": "SRN",
            "locationType": 0,
            "parentStation": "SRN",
            "platformCode": 1,
            "nextStop": "AME3"
        },
        {
            "stopId":"AME3",
            "stopName":"Ameerpet",
            "lat": 17.4357214,
            "long": 78.4447933,
            "zone": "AME_R",
            "locationType": 0,
            "parentStation": "AME",
            "platformCode": 3,
            "is_connected_station": true,
            "connected_platform_ids":["AME1","AME2"],
            "nextStop": "PUN1"
        },
        {
            "stopId":"PUN1",
            "stopName":"Punjagutta",
            "lat": 17.4289362,
            "long": 78.450955,
            "zone": "PUN",
            "locationType": 0,
            "parentStation": "PUN",
            "platformCode": 1,
            "nextStop": "IRM1"
        },
        {
            "stopId":"IRM1",
            "stopName":"Erra Manzil",
            "lat": 17.4202292,
            "long": 78.4563489,
            "zone": "IRM",
            "locationType": 0,
            "parentStation": "IRM",
            "platformCode": 1,
            "nextStop": "KHA1"
        },
        {
            "stopId":"KHA1",
            "stopName":"Khairatabad",
            "lat": 17.4116323,
            "long": 78.4608678,
            "zone": "KHA",
            "locationType": 0,
            "parentStation": "KHA",
            "platformCode": 1,
            "nextStop": "LKP1"
        },{
            "stopId":"LKP1",
            "stopName":"Lakdi-ka-pul",
            "lat": 17.4040433,
            "long": 78.4649442,
            "zone": "LKP",
            "locationType": 0,
            "parentStation": "LKP",
            "platformCode": 1,
            "nextStop": "ASM1"
        },{
            "stopId":"ASM1",
            "stopName":"Assembly",
            "lat": 17.3979907,
            "long": 78.4708797,
            "zone": "ASM",
            "locationType": 1,
            "parentStation": "ASM",
            "platformCode": 1,
            "nextStop": "NAM1"
        },
        {
            "stopId":"NAM1",
            "stopName":"Nampally",
            "lat": 17.392222,
            "long": 78.4701612,
            "zone": "NAM",
            "locationType": 0,
            "parentStation": "NAM",
            "platformCode": 1,
            "nextStop": "GAB1"
        },
        {
            "stopId":"GAB1",
            "stopName":"Gandhi Bhavan",
            "lat": 17.3858253,
            "long": 78.4733347,
            "zone": "GAB",
            "locationType": 0,
            "parentStation": "GAB",
            "platformCode": 1,
            "nextStop": "OMC1"
        },
        {
            "stopId":"OMC1",
            "stopName":"Osmania Medical College",
            "lat": 17.3820769,
            "long": 78.4817011,
            "zone": "OMC",
            "locationType": 0,
            "parentStation": "OMC",
            "platformCode": 1,
            "nextStop": "MGB3"

        },
        {
            "stopId":"MGB3",
            "stopName":"Mahatma Gandhi Bus Station",
            "lat": 17.3797886,
            "long": 78.4861571,
            "zone": "MGB_G",
            "locationType": 0,
            "parentStation": "MGB",
            "is_connected_station": true,
            "connected_platform_ids":["MGB1","MGB2"],
            "platformCode": 3,
            "nextStop": "MKL1"
        },
        {
            "stopId":"MKL1",
            "stopName":"Malakpet",
            "lat": 17.3771888,
            "long": 78.4939356,
            "zone": "MKL",
            "locationType": 0,
            "parentStation": "MKL",
            "platformCode": 1,
            "nextStop": "NEM1"
        },
        {
            "stopId":"NEM1",
            "stopName":"New Market",
            "lat": 17.3734454,
            "long": 78.5031791,
            "zone": "NEM",
            "locationType": 0,
            "parentStation": "NEM",
            "platformCode": 1,
            "nextStop": "MSB1"
        },
        {
            "stopId":"MSB1",
            "stopName":"Musarambagh",
            "lat": 17.3710873,
            "long": 78.5119545,
            "zone": "MSB",
            "locationType": 0,
            "parentStation": "MSB",
            "platformCode": 1,
            "nextStop": "DSN1"
        },
        {  
            "stopId":"DSN1",
            "stopName":"Dilsukh Nagar",
            "lat": 17.3685493,
            "long": 78.5253873,
            "zone": "DSN",
            "locationType": 0,
            "parentStation": "DSN",
            "platformCode": 1,
            "nextStop": "CHP1"
        },
        {
            "stopId":"CHP1",
            "stopName":"Chaitanyapuri",
            "lat": 17.3681501,
            "long": 78.5381335,
            "zone": "CHP",
            "locationType": 0,
            "parentStation": "CHP",
            "platformCode": 1,
            "nextStop": "VOM1"
        },
        {
            "stopId":"VOM1",
            "stopName":"victoria memorial",
            "lat": 17.3618565,
            "long": 78.5439622,
            "zone": "VOM",
            "locationType": 0,
            "parentStation": "VOM",
            "platformCode": 1,
            "nextStop": "LBN1" 
        },
        {
            "stopId":"LBN1",
            "stopName":"L. B. Nagar",
            "lat": 17.349846,
            "long": 78.5479412,
            "zone": "LBN",
            "locationType": 0,
            "parentStation": "LBN",
            "platformCode": 1,
            "nextStop": ""
        }
    ],
    "stops-2-way":[
        {
            "stopId": "LBN2",
            "stopName": "L. B. Nagar",
            "lat": 17.349846,
            "long": 78.5479412,
            "zone": "LBN",
            "locationType": 0,
            "parentStation": "LBN",
            "platformCode": 2,
            "nextStop": "VOM2"
        },
        {
            "stopId": "VOM2",
            "stopName": "victoria memorial",
            "lat": 17.3618565,
            "long": 78.5439622,
            "zone": "VOM",
            "locationType": 0,
            "parentStation": "VOM",
            "platformCode": 2,
            "nextStop": "CHP2"
        },
        {
            "stopId": "CHP2",
            "stopName": "Chaitanyapuri",
            "lat": 17.3681501,
            "long": 78.5381335,
            "zone": "CHP",
            "locationType": 0,
            "parentStation": "CHP",
            "platformCode": 2,
            "nextStop": "DSN2"
        },
        {
            "stopId": "DSN2",
            "stopName": "Dilsukh Nagar",
            "lat": 17.3685493,
            "long": 78.5253873,
            "zone": "DSN",
            "locationType": 0,
            "parentStation": "DSN",
            "platformCode": 2,
            "nextStop": "MSB2"
        },
        {
            "stopId": "MSB2",
            "stopName": "Musarambagh",
            "lat": 17.3710873,
            "long": 78.5119545,
            "zone": "MSB",
            "locationType": 0,
            "parentStation": "MSB",
            "platformCode": 2,
            "nextStop": "NEM2"
        },
        {
            "stopId": "NEM2",
            "stopName": "New Market",
            "lat": 17.3734454,
            "long": 78.5031791,
            "zone": "NEM",
            "locationType": 0,
            "parentStation": "NEM",
            "platformCode": 2,
            "nextStop": "MKL2"
        },
        {
            "stopId": "MKL2",
            "stopName": "Malakpet",
            "lat": 17.3771888,
            "long": 78.4939356,
            "zone": "MKL",
            "locationType": 0,
            "parentStation": "MKL",
            "platformCode": 2,
            "nextStop": "MGB4"
        },
        {
            "stopId": "MGB4",
            "stopName": "Mahatma Gandhi Bus Station",
            "lat": 17.3797886,
            "long": 78.4861571,
            "zone": "MGB_G",
            "locationType": 0,
            "parentStation": "MGB",
            "is_connected_station": true,
            "connected_platform_ids":["MGB1","MGB2"],
            "platformCode": 4,
            "nextStop": "OMC2"
        },
        {
            "stopId": "OMC2",
            "stopName": "Osmania Medical College",
            "lat": 17.3820769,
            "long": 78.4817011,
            "zone": "OMC",
            "locationType": 0,
            "parentStation": "OMC",
            "platformCode": 2,
            "nextStop": "GAB2"
        },
        {
            "stopId": "GAB2",
            "stopName": "Gandhi Bhavan",
            "lat": 17.3858253,
            "long": 78.4733347,
            "zone": "GAB",
            "locationType": 0,
            "parentStation": "GAB",
            "platformCode": 2,
            "nextStop": "NAM2"
        },
        {
            "stopId": "NAM2",
            "stopName": "Nampally",
            "lat": 17.392222,
            "long": 78.4701612,
            "zone": "NAM",
            "locationType": 0,
            "parentStation": "NAM",
            "platformCode": 2,
            "nextStop": "ASM2"
        },
        {
            "stopId": "ASM2",
            "stopName": "Assembly",
            "lat": 17.3979907,
            "long": 78.4708797,
            "zone": "ASM",
            "locationType": 1,
            "parentStation": "ASM",
            "platformCode": 2,
            "nextStop": "LKP2"
        },
        {
            "stopId": "LKP2",
            "stopName": "Lakdi-ka-pul",
            "lat": 17.4040433,
            "long": 78.4649442,
            "zone": "LKP",
            "locationType": 0,
            "parentStation": "LKP",
            "platformCode": 2,
            "nextStop": "KHA2"
        },
        {
            "stopId": "KHA2",
            "stopName": "Khairatabad",
            "lat": 17.4116323,
            "long": 78.4608678,
            "zone": "KHA",
            "locationType": 0,
            "parentStation": "KHA",
            "platformCode": 2,
            "nextStop": "IRM2"
        },
        {
            "stopId": "IRM2",
            "stopName": "Erra Manzil",
            "lat": 17.4202292,
            "long": 78.4563489,
            "zone": "IRM",
            "locationType": 0,
            "parentStation": "IRM",
            "platformCode": 2,
            "nextStop": "PUN2"
        },
        {
            "stopId": "PUN2",
            "stopName": "Punjagutta",
            "lat": 17.4289362,
            "long": 78.450955,
            "zone": "PUN",
            "locationType": 0,
            "parentStation": "PUN",
            "platformCode": 2,
            "nextStop": "AME3"
        },
        {
            "stopId": "AME3",
            "stopName": "Ameerpet",
            "lat": 17.4357214,
            "long": 78.4447933,
            "zone": "AME_R",
            "locationType": 0,
            "parentStation": "AME",
            "platformCode": 4,
            "is_connected_station": true,
            "connected_platform_ids":["AME1","AME2"],
            "nextStop": "SRN2"
        },
        {
            "stopId": "SRN2",
            "stopName": "S. R. Nagar",
            "lat": 17.4431205,
            "long": 78.4407241,
            "zone": "SRN",
            "locationType": 0,
            "parentStation": "SRN",
            "platformCode": 2,
            "nextStop": "ESI2"
        },
        {
            "stopId": "ESI2",
            "stopName": "ESI Hospital",
            "lat": 17.4486969,
            "long": 78.4376283,
            "zone": "ESI",
            "locationType": 0,
            "parentStation": "ESI",
            "platformCode": 2,
            "nextStop": "ERA2"
        },
        {
            "stopId": "ERA2",
            "stopName": "Erragadda",
            "lat": 17.4570487,
            "long": 78.4335811,
            "zone": "ERA",
            "locationType": 0,
            "parentStation": "ERA",
            "platformCode": 2,
            "nextStop": "BTN2"
        },
        {
            "stopId": "BTN2",
            "stopName": "Bharat Nagar",
            "lat": 17.4629092,
            "long": 78.4305364,
            "zone": "BTN",
            "locationType": 0,
            "parentStation": "BTN",
            "platformCode": 2,
            "nextStop": "MSP2"
        },
        {
            "stopId": "MSP2",
            "stopName": "Moosapet",
            "lat": 17.4718855,
            "long": 78.4261182,
            "zone": "MSP",
            "locationType": 0,
            "parentStation": "MSP",
            "platformCode": 2,
            "nextStop": "BLR2"
        },
        {
            "stopId": "BLR2",
            "stopName": "Balanagar",
            "lat": 17.4767464,
            "long": 78.4221082,
            "zone": "BLR",
            "locationType": 0,
            "parentStation": "BLR",
            "platformCode": 2,
            "nextStop": "KUK2"
        },
        {
            "stopId": "KUK2",
            "stopName": "Kukatpally",
            "lat": 17.4849033,
            "long": 78.4117896,
            "zone": "KUK",
            "locationType": 0,
            "parentStation": "KUK",
            "platformCode": 2,
            "nextStop": "KPH2"
        },
        {
            "stopId": "KPH2",
            "stopName": "KPHB",
            "lat": 17.4937602,
            "long": 78.4018258,
            "zone": "KPH",
            "locationType": 0,
            "parentStation": "KPH",
            "platformCode": 2,
            "nextStop": "JNT2"
        },
        {
            "stopId": "JNT2",
            "stopName": "JNTU College",
            "lat": 17.4987037,
            "long": 78.3888668,
            "zone": "JNT",
            "locationType": 0,
            "parentStation": "JNT",
            "platformCode": 2,
            "nextStop": "MYP2"
        },
        {
            "stopId": "MYP2",
            "stopName": "Miyapur",
            "lat": 17.4965452,
            "long": 78.3730262,
            "zone": "MYP",
            "locationType": 0,
            "parentStation": "MYP",
            "platformCode": 2,
            "nextStop": ""
        }
    ]

},
{
    "route": "Blue Line",
    "line": "Blue",
    "parentStopIds":["NAG","UPL","STD","NGR","HSG","TAR","MET","SEC","PRG","PAR","ROP","PRN","BEG","AME","MUN","YUG","JR5","JCP","PED","MAD","DGC","HTC","RDG"],
    "stops-1-way-stopIds":["NAG1","UPL1","STD1","NGR1","HSG1","TAR1","MET1","SEC1","PRG1","PAR1","ROP1","PRN1","BEG1","AME1","MUN1","YUG1","JR51","JCP1","PED1","MAD1","DGC1","HTC1","RDG1"],
    "stops-2-way-stopIds":["RDG2","HTC2","DGC2","MAD2","PED2","JCP2","JR52","YUG2","MUN2","AME2","BEG2","PRN2","ROP2","PAR2","PRG2","SEC2","MET2","TAR2","HSG2","NGR2","STD2","UPL2","NAG2"],
    "stops-1-way":[
        {
            "stopId": "NAG1",
            "stopName": "Nagole",
            "lat": 17.3907683,
            "long": 78.5588222,
            "zone": "NAG",
            "locationType": 0,
            "parentStation": "NAG",
            "platformCode": 1,
            "nextStop": "UPL1"
        },
        {
            "stopId": "UPL1",
            "stopName": "Uppal",
            "lat": 17.4000665,
            "long": 78.5601868,
            "zone": "UPL",
            "locationType": 0,
            "parentStation": "UPL",
            "platformCode": 1,
            "nextStop": "STD1"
        },
        {
            "stopId": "STD1",
            "stopName": "Stadium",
            "lat": 17.4074002,
            "long": 78.5542531,
            "zone": "STD",
            "locationType": 0,
            "parentStation": "STD",
            "platformCode": 1,
            "nextStop": "NGR1"
        },
        {
            "stopId": "NGR1",
            "stopName": "NGRI",
            "lat": 17.4148264,
            "long": 78.5463345,
            "zone": "NGR",
            "locationType": 0,
            "parentStation": "NGR",
            "platformCode": 1,
            "nextStop": "HSG1"
        },
        {
            "stopId": "HSG1",
            "stopName": "Habsiguda",
            "lat": 17.42018,
            "long": 78.540548,
            "zone": "HSG",
            "locationType": 0,
            "parentStation": "HSG",
            "platformCode": 1,
            "nextStop": "TAR1"
        },
        {
            "stopId": "TAR1",
            "stopName": "Tarnaka",
            "lat": 17.4274418,
            "long": 78.5300079,
            "zone": "TAR",
            "locationType": 0,
            "parentStation": "TAR",
            "platformCode": 1,
            "nextStop": "MET1"
        },
        {
            "stopId": "MET1",
            "stopName": "Mettuguda",
            "lat": 17.4355207,
            "long": 78.5195754,
            "zone": "MET",
            "locationType": 0,
            "parentStation": "MET",
            "platformCode": 1,
            "nextStop": "SEC1"
        },
        {
            "stopId": "SEC1",
            "stopName": "Secunderabad East",
            "lat": 17.4357184,
            "long": 78.5054623,
            "zone": "SEC_E",
            "locationType": 0,
            "parentStation": "SEC_E",
            "platformCode": 1,
            "nextStop": "PRG1"
        },
        {
            "stopId": "PRG1",
            "stopName": "Parade Ground",
            "lat": 17.4431943,
            "long": 78.4974687,
            "zone": "PRG",
            "locationType": 0,
            "parentStation": "PRG",
            "platformCode": 1,
            "is_connected_station": true,
            "connected_platform_ids":["PRG3","PRG4"],
            "nextStop": "PAR1"
        },
        {
            "stopId": "PAR1",
            "stopName": "Paradise",
            "lat": 17.4434668,
            "long": 78.4862436,
            "zone": "PAR",
            "locationType": 0,
            "parentStation": "PAR",
            "platformCode": 1,
            "nextStop": "ROP1"
        },
        {
            "stopId": "ROP1",
            "stopName": "Rasoolpura",
            "lat": 17.443612,
            "long": 78.4764053,
            "zone": "ROP",
            "locationType": 0,
            "parentStation": "ROP",
            "platformCode": 1,
            "nextStop": "PRN1"
        },
        {
            "stopId": "PRN1",
            "stopName": "Prakash Nagar",
            "lat": 17.4448889,
            "long": 78.4658749,
            "zone": "PRN",
            "locationType": 0,
            "parentStation": "PRN", 
            "platformCode": 1,
            "nextStop": "BEG1"
        },
        {
            "stopId": "BEG1",
            "stopName": "Begumpet",
            "lat": 17.4375661,
            "long": 78.4569341,
            "zone": "BEG",
            "locationType": 0,
            "parentStation": "BEG",
            "platformCode": 1,
            "nextStop": "MUN1"
        },
        {
            "stopId": "MUN1",
            "stopName": "Madhura Nagar",
            "lat": 17.4369652,
            "long": 78.4390993,
            "zone": "MUN",
            "locationType": 0,
            "parentStation": "MUN",
            "platformCode": 1,
            "nextStop": "YUG1"
        },
        {
            "stopId": "YUG1",
            "stopName": "Yusufguda",
            "lat": 17.4351132,
            "long": 78.4273216,
            "zone": "YUG",
            "locationType": 0,
            "parentStation": "YUG",
            "platformCode": 1,
            "nextStop": "JR51"
        },
        {
            "stopId": "JR51",
            "stopName": "Road No 5 Jubilee Hills",
            "lat": 17.4300489,
            "long": 78.4232069,
            "zone": "JR5",
            "locationType": 0,
            "parentStation": "JR5",
            "platformCode": 1,
            "nextStop": "JCP1"
        },
        {
            "stopId": "JCP1",
            "stopName": "Jubilee Check Post",
            "lat": 17.424893,
            "long": 78.418101,
            "zone": "JCP",
            "locationType": 0,
            "parentStation": "JCP",
            "platformCode": 1,
            "nextStop": "PED1"
        },
        {
            "stopId": "PED1",
            "stopName": "Pedamma Temple",
            "lat": 17.420893,
            "long": 78.413101,
            "zone": "PED",
            "locationType": 0,
            "parentStation": "PED",
            "platformCode": 1,
            "nextStop": "MAD1"  
        },
        {
            "stopId": "MAD1",
            "stopName": "Madhapur",
            "lat": 17.415893,
            "long": 78.408101,
            "zone": "MAD",
            "locationType": 0,
            "parentStation": "MAD",
            "platformCode": 1,
            "nextStop": "DGC1"
        },
        {
            "stopId": "DGC1",
            "stopName": "Durgam Cheruvu",
            "lat": 17.410893,
            "long": 78.403101,
            "zone": "DGC",
            "locationType": 0,
            "parentStation": "DGC",
            "platformCode": 1,
            "nextStop": "HTC1"
        },
        {
            "stopId": "HTC1",
            "stopName": "Hitec City",
            "lat": 17.405893,
            "long": 78.398101,
            "zone": "HTC",
            "locationType": 0,
            "parentStation": "HTC",
            "platformCode": 1,
            "nextStop": "RDG1"
        },
        {
            "stopId": "RDG1",
            "stopName": "Raidurg",
            "lat": 17.400893,
            "long": 78.393101,
            "zone": "RDG",
            "locationType": 0,
            "parentStation": "RDG",
            "platformCode": 1,
            "nextStop": ""
        }
    ],
    "stops-2-way":[
        {
            "stopId": "RDG2",
            "stopName": "Raidurg",
            "lat": 17.400893,
            "long": 78.393101,
            "zone": "RDG",
            "locationType": 0,
            "parentStation": "RDG",
            "platformCode": 2,
            "nextStop": "HTC2"
        },
        {
            "stopId": "HTC2",
            "stopName": "Hitec City",
            "lat": 17.405893,
            "long": 78.398101,
            "zone": "HTC",
            "locationType": 0,
            "parentStation": "HTC",
            "platformCode": 2,
            "nextStop": "DGC2"
        },
        {
            "stopId": "DGC2",
            "stopName": "Durgam Cheruvu",
            "lat": 17.410893,
            "long": 78.403101,
            "zone": "DGC",
            "locationType": 0,
            "parentStation": "DGC",
            "platformCode": 2,
            "nextStop": "MAD2"
        },
        {
            "stopId": "MAD2",
            "stopName": "Madhapur",
            "lat": 17.415893,
            "long": 78.408101,
            "zone": "MAD",
            "locationType": 0,
            "parentStation": "MAD",
            "platformCode": 2,
            "nextStop": "PED2"
        },
        {
            "stopId": "PED2",
            "stopName": "Pedamma Temple",
            "lat": 17.420893,
            "long": 78.413101,
            "zone": "PED",
            "locationType": 0,
            "parentStation": "PED",
            "platformCode": 2,
            "nextStop": "JCP2"
        },
        {
            "stopId": "JCP2",
            "stopName": "Jubilee Check Post",
            "lat": 17.424893,
            "long": 78.418101,
            "zone": "JCP",
            "locationType": 0,
            "parentStation": "JCP",
            "platformCode": 2,
            "nextStop": "JR52"
        },
        {
            "stopId": "JR52",
            "stopName": "Road No 5 Jubilee Hills",
            "lat": 17.4300489,
            "long": 78.4232069,
            "zone": "JR5",
            "locationType": 0,
            "parentStation": "JR5",
            "platformCode": 2,
            "nextStop": "YUG2"
        },
        {
            "stopId": "YUG2",
            "stopName": "Yusufguda",
            "lat": 17.4351132,
            "long": 78.4273216,
            "zone": "YUG",
            "locationType": 0,
            "parentStation": "YUG",
            "platformCode": 2,
            "nextStop": "MUN2"
        },
        {
            "stopId": "MUN2",
            "stopName": "Madhura Nagar",
            "lat": 17.4369652,
            "long": 78.4390993,
            "zone": "MUN",
            "locationType": 0,
            "parentStation": "MUN",
            "platformCode": 2,
            "nextStop": "BEG2"
        },
        {
            "stopId": "BEG2",
            "stopName": "Begumpet",
            "lat": 17.4375661,
            "long": 78.4569341,
            "zone": "BEG",
            "locationType": 0,
            "parentStation": "BEG",
            "platformCode": 2,
            "nextStop": "PRN2"
        },
        {
            "stopId": "PRN2",
            "stopName": "Prakash Nagar",
            "lat": 17.4448889,
            "long": 78.4658749,
            "zone": "PRN",
            "locationType": 0,
            "parentStation": "PRN",
            "platformCode": 2,
            "nextStop": "ROP2"
        },
        {
            "stopId": "ROP2",
            "stopName": "Rasoolpura",
            "lat": 17.443612,
            "long": 78.4764053,
            "zone": "ROP",
            "locationType": 0,
            "parentStation": "ROP",
            "platformCode": 2,
            "nextStop": "PAR2"
        },
        {
            "stopId": "PAR2",
            "stopName": "Paradise",
            "lat": 17.4434668,
            "long": 78.4862436,
            "zone": "PAR",
            "locationType": 0,
            "parentStation": "PAR",
            "platformCode": 2,
            "nextStop": "PRG2"
        },
        {
            "stopId": "PRG2",
            "stopName": "Parade Ground",
            "lat": 17.4431943,
            "long": 78.4974687,
            "zone": "PRG",
            "locationType": 0,
            "parentStation": "PRG",
            "is_connected_station": true,
            "connected_platform_ids":["PRG3","PRG4"],
            "platformCode": 2,
            "nextStop": "SEC1"
        },
        {
            "stopId": "SEC1",
            "stopName": "Secunderabad East",
            "lat": 17.4357184,
            "long": 78.5054623,
            "zone": "SEC_E",
            "locationType": 0,
            "parentStation": "SEC_E",
            "platformCode": 2,
            "nextStop": "MET1"
        },
        {
            "stopId": "MET1",
            "stopName": "Mettuguda",
            "lat": 17.4355207,
            "long": 78.5195754,
            "zone": "MET",
            "locationType": 0,
            "parentStation": "MET",
            "platformCode": 2,
            "nextStop": "TAR1"
        },
        {
            "stopId": "TAR2",
            "stopName": "Tarnaka",
            "lat": 17.4274418,
            "long": 78.5300079,
            "zone": "TAR",
            "locationType": 0,
            "parentStation": "TAR",
            "platformCode": 2,
            "nextStop": "HSG2"
        },
        {
            "stopId": "HSG2",
            "stopName": "Habsiguda",
            "lat": 17.42018,
            "long": 78.540548,
            "zone": "HSG",
            "locationType": 0,
            "parentStation":"HSG",
            "platformCode": 2,
            "nextStop":"NGR2"
        },
        {
            "stopId": "NGR2",
            "stopName": "NGRI",
            "lat": 17.4148264,
            "long": 78.5463345,
            "zone": "NGR",
            "locationType": 0,
            "parentStation": "NGR",
            "platformCode": 2,
            "nextStop": "STD2"
        },
        {
            "stopId":"STD2",
            "stopName":"Stadium",
            "lat": 17.4074002,
            "long": 78.5542531,
            "zone": "STD",
            "locationType": 0,
            "parentStation": "STD",
            "platformCode": 2,
            "nextStop": "UPL2"
        },
        {
            "stopId":"UPL2",
            "stopName":"Uppal",
            "lat": 17.4000665,
            "long": 78.5601868,
            "zone": "UPL",
            "locationType": 0,
            "parentStation": "UPL",
            "platformCode": 2,
            "nextStop": "NAG2"
        },
        {
            "stopId":"NAG2",
            "stopName":"Nagole",
            "lat": 17.3907683,
            "long": 78.5588222,
            "zone": "NAG",
            "locationType": 0,
            "parentStation": "NAG",
            "platformCode": 2,
            "nextStop": ""
        } 
    ]
},
{
    "route": "Green Line",
    "line": "Green",
    "parentStopIds":["MGB","SUB","NAR","CDP","RTC","MSH","GNH","SCR","PRG","JBS"],
    "stops-1-way-stopIds":["MGB1","SUB1","NAR1","CDP1","RTC1","MSH1","GNH1","SCR1","PRG3"],
    "stops-2-way-stopIds":["PRG4","SCR2","GNH2","MSH2","RTC2","CDP2","NAR2","SUB2","MGB2"],
    "stops-1-way": [
        {
            "stopId": "MGB1",
            "stopName": "MG Road",
            "lat": 17.4431943,
            "long": 78.4974687,
            "zone": "MGB",
            "locationType": 0,
            "parentStation": "MGB",
            "platformCode": 1,
            "nextStop": "SUB1"
        },
        {
            "stopId": "SUB1",
            "stopName": "Sultan Bazar",
            "lat": 17.3844473,
            "long": 78.4840241,
            "zone": "SUB",
            "locationType": 0,
            "parentStation": "SUB",
            "platformCode": 1,
            "nextStop": "NAR1"
        },
        {
            "stopId": "NAR1",
            "stopName": "Narayanguda",
            "lat": 17.3943658,
            "long": 78.4899578,
            "zone": "NAR",
            "locationType": 0,
            "parentStation": "NAR",
            "platformCode": 1,
            "nextStop": "CDP1"
        },
        {
            "stopId": "CDP1",
            "stopName": "Chandrayanguda",
            "lat": 17.4003634,
            "long": 78.4948964,
            "zone": "CDP",
            "locationType": 0,
            "parentStation": "CDP",
            "platformCode": 1,
            "nextStop": "RTC1"
        },
        {
            "stopId": "RTC1",
            "stopName": "R.T. Nagar",
            "lat": 17.4070321,
            "long": 78.4968023,
            "zone": "RTC",
            "locationType": 0,
            "parentStation": "RTC",
            "platformCode": 1,
            "nextStop": "MSH1"
        },
        {
            "stopId": "MSH1",
            "stopName":"Musheedabad",
            "lat": 17.4178744,
            "long": 78.4995051,
            "zone": "MSH",
            "locationType": 0,
            "parentStation": "MSH",
            "platformCode": 1,
            "nextStop": "GNH1"
        },
        {
            "stopId":"GNH1",
            "stopName":"Gandhi Nagar",
            "lat": 17.4255155,
            "long": 78.501956,
            "zone": "GNH",
            "locationType": 0,
            "parentStation": "GNH",
            "platformCode": 1,
            "nextStop": "SCR1"
        },
        {
            "stopId":"SCR1",
            "stopName":"Secunderabad Cantonment",
            "lat": 17.4338034,
            "long": 78.4995181,
            "zone": "SCR",
            "locationType": 0,
            "parentStation": "SCR",
            "platformCode": 1,
            "nextStop": "PG3"
        },
        {
            "stopId":"PRG3",
            "stopName":"Jbs parade ground",
            "lat": 17.4444775,
            "long": 78.497584,
            "zone": "PRG",
            "locationType": 0,
            "is_connected_station": true,
            "connected_platform_ids":["PRG1","PRG2"],
            "parentStation": "PRG",
            "platformCode": 1,
            "nextStop": ""
        }
    ],
    "stops-2-way": [
        {
            "stopId":"PRG4",
            "stopName":"Jbs parade ground",
            "lat": 17.4444775,
            "long": 78.497584,
            "zone": "PRG4",
            "locationType": 0,
            "parentStation": "PRG",
            "is_connected_station": true,
            "connected_platform_ids":["PRG1","PRG2"],
            "platformCode": 4,
            "nextStop": "SCR2"
        },
        {
            "stopId":"SCR2",
            "stopName":"Secunderabad Cantonment",
            "lat": 17.4338034,
            "long": 78.4995181,
            "zone": "SCR",
            "locationType": 0,
            "parentStation": "SCR",
            "platformCode": 2,
            "nextStop": "GNH2"
        },
        {
            "stopId":"GNH2",
            "stopName":"Gandhi Nagar",
            "lat": 17.4255155,
            "long": 78.501956,
            "zone": "GNH",
            "locationType": 0,
            "parentStation": "GNH",
            "platformCode": 2,
            "nextStop": "MSH2"
        },
        {
            "stopId":"MSH2",
            "stopName":"Musheedabad",
            "lat": 17.4178744,
            "long": 78.4995051,
            "zone": "MSH",
            "locationType": 0,
            "parentStation": "MSH",
            "platformCode": 2,
            "nextStop": "RTC2"
        },
        {
            "stopId":"RTC2",
            "stopName":"R.T. Nagar",
            "lat": 17.4070321,
            "long": 78.4968023,
            "zone": "RTC",
            "locationType": 0,
            "parentStation": "RTC",
            "platformCode": 2,
            "nextStop": "CDP2"
        },
        {
            "stopId":"CDP2",
            "stopName":"Chandrayanguda",
            "lat": 17.4003634,
            "long": 78.4948964,
            "zone": "CDP",
            "locationType": 0,
            "parentStation": "CDP",
            "platformCode": 2,
            "nextStop": "NAR2"
        },
        {
            "stopId":"NAR2",
            "stopName":"Narayanguda",
            "lat": 17.3943658,
            "long": 78.4899578,
            "zone": "NAR",
            "locationType": 0,
            "parentStation": "NAR",
            "platformCode": 2,
            "nextStop": "SUB2"
        },
        {
            "stopId":"SUB2",
            "stopName":"Sultan Bazar",
            "lat": 17.3844473,
            "long": 78.4840241,
            "zone": "SUB",
            "locationType": 0,
            "parentStation": "SUB",
            "platformCode": 2,
            "nextStop": "MGB2"
        },
        {
            "stopId":"MGB2",
            "stopName":"MG Road",
            "lat": 17.4431943,
            "long": 78.4974687,
            "zone": "MGB",
            "locationType": 0,
            "parentStation": "MGB",
            "platformCode": 2,
            "nextStop": ""
        }
    ]
}
]

export default metroData;